# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Tachy2GIS
                                 A QGIS plugin
 Dragons
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-11
        copyright            : (C) 2019 by ufg kiel
        email                : ufg kiel
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Tachy2GIS class from file Tachy2GIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tachy2gis import Tachy2GIS
    return Tachy2GIS(iface)
